# Generated by Django 2.2.26 on 2022-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220523_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
